#expected units rad, deg, rev
AngularMeasurement position
#expected units rad, deg, rev
AngularMeasurement velocity_feedforward
#expected units nm
AngularMeasurement torque_feedforward
---
bool success