name: 'Run TODO to Issue'
on: ['push']

permissions:
    issues: write
    contents: read

jobs:
    todo-to-issue:
        runs-on: 'ubuntu-latest'
        permissions:
            issues: write
        steps:
            - uses: 'actions/checkout@v4'
              with:
                  repository: UA-NASA-Robotics/Roobot-Over-IP

            - name: 'TODO to Issue'
              uses: 'alstr/todo-to-issue-action@v5'
